
data:
  data_path: '/home/ourobros/add_test/data_day/'
  future1_name: 'DCE.jm88'
  future2_name: 'CZCE.SM88'

preprocess_data:
  MOMENTUM_PERIOD: 15
  WINDOW: 30
  WINDOW_FAST: 10
  WINDOW_SLOW: 30

train:
  epochs: 10
  ts_length: 1
  device: 'cuda:0'
  train_data_precent: 0.6

backtest:
  start_time: '2021-10-10 00:00:00'
  end_time: '2022-01-10 23:59:59'


